### ISSUE TITLE
[решение] как в browser-sync поменять браузер по умолчанию на другой

### ISSUE THREAD

**Issue by Sellato** [tars/tars-cli#128]
Столкнулся с проблемой, что не могу поменять браузер по умолчанию на `chrome`

Казалось бы правим файл `plugins-config.json` и получем исконный результат, и даже подсказка для тупых есть, бери да делай!
Ан-нет на Linux не работает эта самая подсказака.

```
        // Choose browser to open
        // @type {String|Array}
        // Example: ['google chrome', 'firefox']
        // Avalible: safari, internet explorer, google chrome, firefox, opera
        "browser": "default",
        "injectChanges": false
```

при подстановке `google chrome` или `chrome` получаем большой облом, нет такого браузера :(

Лечится это тривиально :)
1. Находим ярлык Google Chrome
2. Правой клавишей выши вызываем меню
3. Выбираем пункт `"Изменить Приложение"`
4. Смотрим, что указано в строке `Комманда:`
5. Вот это и прописываем в конфиг

у меня `Google Chrome` прописан как `google-chrome-stable`

вот, что получилось

```
        // Choose browser to open
        // @type {String|Array}
        // Example: ['google chrome', 'firefox']
        // Avalible: safari, internet explorer, google chrome, firefox, opera
        "browser": "google-chrome-stable",
        "injectChanges": false
```

Теперь все как надо, вызывается `Google Chrome`

Всем удачи!

**Comment by Sellato** [comment]
А вот массив из баузеров подключить не удалось :(
Строка 

`"browser": ["google-chrome-stable", "vivaldi","firefox", "opera"]`

Приводит к ошибке:

```
SyntaxError: Unexpected token "
    at unexpected (/home/igor/.nvm/versions/node/v14.13.1/lib/node_modules/tars-cli/node_modules/comment-json/src/parse.js:80:17)
    at expect (/home/igor/.nvm/versions/node/v14.13.1/lib/node_modules/tars-cli/node_modules/comment-json/src/parse.js:125:5)
    at parse_object (/home/igor/.nvm/versions/node/v14.13.1/lib/node_modules/tars-cli/node_modules/comment-json/src/parse.js:209:7)
    at walk (/home/igor/.nvm/versions/node/v14.13.1/lib/node_modules/tars-cli/node_modules/comment-json/src/parse.js:304:12)
    at parse_object (/home/igor/.nvm/versions/node/v14.13.1/lib/node_modules/tars-cli/node_modules/comment-json/src/parse.js:232:33)
    at walk (/home/igor/.nvm/versions/node/v14.13.1/lib/node_modules/tars-cli/node_modules/comment-json/src/parse.js:304:12)
    at Object.parse (/home/igor/.nvm/versions/node/v14.13.1/lib/node_modules/tars-cli/node_modules/comment-json/src/parse.js:356:16)
    at makePluginsConfig (/home/igor/developer/landings/tars-cli/tars/helpers/plugins-config-processing.js:11:35)
    at Object.<anonymous> (/home/igor/developer/landings/tars-cli/tars/tars.js:68:76)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  line: 18,
  column: 8
```

и похоже это уже проблемы TARS

```
    at makePluginsConfig (/home/igor/developer/landings/tars-cli/tars/helpers/plugins-config-processing.js:11:35)
    at Object.<anonymous> (/home/igor/developer/landings/tars-cli/tars/tars.js:68:76)
```

Интересует ваше мнение :)

**Comment by artem-malko** [comment]
@Sellato а не хочешь стать мейнтейнером проекта?)

**Comment by Sellato** [comment]
смеешься, я только начал топтаться по этой теме :)

**Comment by artem-malko** [comment]
@Sellato мне кажется, у тебя хорошо выходит разбираться!
