### ISSUE TITLE
TypeError: Class constructor CommentArray cannot be invoked without 'new'

### ISSUE THREAD

**Issue by gagmgm** [tars/tars-cli#133]
/usr/local/lib/node_modules/tars-cli/node_modules/lodash.clonedeep/index.js:1235
      result = array.constructor(length);
                     ^

TypeError: Class constructor CommentArray cannot be invoked without 'new'
    at initCloneArray (/usr/local/lib/node_modules/tars-cli/node_modules/lodash.clonedeep/index.js:1235:22)
    at baseClone (/usr/local/lib/node_modules/tars-cli/node_modules/lodash.clonedeep/index.js:854:14)
    at /usr/local/lib/node_modules/tars-cli/node_modules/lodash.clonedeep/index.js:897:30
    at arrayEach (/usr/local/lib/node_modules/tars-cli/node_modules/lodash.clonedeep/index.js:140:9)
    at baseClone (/usr/local/lib/node_modules/tars-cli/node_modules/lodash.clonedeep/index.js:891:3)
    at cloneDeep (/usr/local/lib/node_modules/tars-cli/node_modules/lodash.clonedeep/index.js:1399:10)
    at Transform.transfob [as _transform] (/usr/local/lib/node_modules/tars-cli/node_modules/gulp-sass/index.js:112:18)
    at Transform._read (_stream_transform.js:190:10)
    at Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Transform.Writable.write (_stream_writable.js:299:11)
    at DestroyableTransform.ondata (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:198:13)
    at addChunk (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at DestroyableTransform.afterTransform (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_transform.js:91:10)
    at DestroyableTransform.noop [as _transform] (/usr/local/lib/node_modules/tars-cli/node_modules/gulp-plumber/node_modules/through2/through2.js:26:3)
    at DestroyableTransform.Transform._read (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DestroyableTransform.ondata (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:198:13)
    at addChunk (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at DestroyableTransform.sourceMapInit [as _transform] (/usr/local/lib/node_modules/tars-cli/node_modules/gulp-sourcemaps/src/init/index.js:134:10)
    at DestroyableTransform.Transform._read (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at write (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:198:13)
    at emitReadable_ (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
    at TransformState.afterTransform (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at DestroyableTransform.noop [as _transform] (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/through2.js:26:3)
    at DestroyableTransform.Transform._read (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:198:13)
    at emitReadable_ (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
    at TransformState.afterTransform (/Users/gagmgm/Documents/projects/estateguru-front/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at /Users/gagmgm/Documents/projects/estateguru-front/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:12:5
    at /Users/gagmgm/Documents/projects/estateguru-front/node_modules/graceful-fs/graceful-fs.js:115:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

**Comment by gagmgm** [comment]
This error I get during runing tars dev task

**Comment by evilsprut** [comment]
OS? NodeJS version? TARS version?

**Comment by GeorgeBekh** [comment]
Same issue
Debian 11
node v10.24.1
tars 1.13.1

**Comment by artem-malko** [comment]
@GeorgeBekh try to use v14.x.x
