### ISSUE TITLE
TypeError: Class constructor CommentArray cannot be invoked without 'new'

### ISSUE THREAD

**Issue by lutskovsky** [tars/tars-cli#134]
```
[15:46:28] 'css:compile-css' errored after 725 ms
[15:46:28] TypeError: Class constructor CommentArray cannot be invoked without 'new'
    at initCloneArray (/usr/local/lib/node_modules/tars-cli/node_modules/lodash.clonedeep/index.js:1235:22)
    at baseClone (/usr/local/lib/node_modules/tars-cli/node_modules/lodash.clonedeep/index.js:854:14)
    at /usr/local/lib/node_modules/tars-cli/node_modules/lodash.clonedeep/index.js:897:30
    at arrayEach (/usr/local/lib/node_modules/tars-cli/node_modules/lodash.clonedeep/index.js:140:9)
    at baseClone (/usr/local/lib/node_modules/tars-cli/node_modules/lodash.clonedeep/index.js:891:3)
    at cloneDeep (/usr/local/lib/node_modules/tars-cli/node_modules/lodash.clonedeep/index.js:1399:10)
    at Transform._transform (/usr/local/lib/node_modules/tars-cli/node_modules/gulp-sass/index.js:112:18)
    at Transform._write (node:internal/streams/transform:171:8)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)
    at Transform.Writable.write (node:internal/streams/writable:508:10)
    at write (/usr/local/lib/node_modules/tars-cli/node_modules/gulp-importify/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/usr/local/lib/node_modules/tars-cli/node_modules/gulp-importify/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/usr/local/lib/node_modules/tars-cli/node_modules/gulp-importify/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (node:events:519:28)
    at DestroyableTransform.emit (node:domain:551:15)
    at emitReadable_ (/usr/local/lib/node_modules/tars-cli/node_modules/gulp-importify/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/usr/local/lib/node_modules/tars-cli/node_modules/gulp-importify/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/usr/local/lib/node_modules/tars-cli/node_modules/gulp-importify/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/usr/local/lib/node_modules/tars-cli/node_modules/gulp-importify/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/usr/local/lib/node_modules/tars-cli/node_modules/gulp-importify/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at DestroyableTransform.endStream [as _flush] (/usr/local/lib/node_modules/tars-cli/node_modules/gulp-importify/index.js:126:14)
    at DestroyableTransform.<anonymous> (/usr/local/lib/node_modules/tars-cli/node_modules/gulp-importify/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at Object.onceWrapper (node:events:633:28)
    at DestroyableTransform.emit (node:events:531:35)
    at DestroyableTransform.emit (node:domain:551:15)
    at finishMaybe (/usr/local/lib/node_modules/tars-cli/node_modules/gulp-importify/node_modules/readable-stream/lib/_stream_writable.js:371:12)
    at endWritable (/usr/local/lib/node_modules/tars-cli/node_modules/gulp-importify/node_modules/readable-stream/lib/_stream_writable.js:378:3)
    at DestroyableTransform.Writable.end (/usr/local/lib/node_modules/tars-cli/node_modules/gulp-importify/node_modules/readable-stream/lib/_stream_writable.js:356:5)
    at DestroyableTransform.onend (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (node:events:633:28)
    at DestroyableTransform.emit (node:events:531:35)
    at DestroyableTransform.emit (node:domain:551:15)
    at endReadableNT (/usr/local/lib/node_modules/tars-cli/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

The error occurs during tars build.

OS: Ubuntu 20.04.5 (WSL)
Node v20.16.0
TARS-CLI version: "1.13.1"
TARS version in current project: "1.15.1"

**Comment by artem-malko** [comment]
Try to use older NodeJS version. Something like 16

**Comment by lutskovsky** [comment]
> Try to use older NodeJS version. Something like 16

не помогает

**Comment by artem-malko** [comment]
@lutskovsky пока могу предложить перейти на еще более старую версию NodeJS с помощью n или nvm. Пока не могу помочь подробнее(
