### ISSUE TITLE
Error: Package gulp-svg-symbols is not available.

### ISSUE THREAD

**Issue by ncer** [tars/tars-cli#135]
**Окружение:**
MacOS Sequoia 15.0.1 (24A348) / Windows 10 (Версия 22H2, Сборка ОС 19045.5011)
NodeJS 16.20.2
npm 8.19.4
🅃 🄰 🅁 🅂 : TARS-CLI version: "1.13.1"
🅃 🄰 🅁 🅂 : TARS version in current project: "1.15.1"

---

Есть проект на тарсе с запуском команд через tars-cli. До сегодняшнего дня таски прекрасно запускались (на mac и windows с конфигурацией описанной выше).

Но что-то пошло не так, когда коллега клонировал репу с проектом и поставил все с нуля, в том числе tars-cli. Сборка начала спотыкаться на пакете gulp-svg-symbols, утверждая что его нет:

```bash
~/frontend git:[develop]
tars dev -l


⠋🅃 🄰 🅁 🅂 : Development task has been started!

⠋🅃 🄰 🅁 🅂 : Build options (active are green): 
⠋🅃 🄰 🅁 🅂 : Server for tunnel and livereload will be started "-t".
⠋🅃 🄰 🅁 🅂 : ✓ Server for livereload will be started.
⠋🅃 🄰 🅁 🅂 : IE8 maintenance "--ie8".
⠋🅃 🄰 🅁 🅂 : IE9 maintenance "--ie9".
⠋🅃 🄰 🅁 🅂 : IE8 and IE9 maintenance "--ie".
⠋🅃 🄰 🅁 🅂 : Custom flags. "--custom-flags" 'customFlags, with space separator'


⠋🅃 🄰 🅁 🅂 : Execute "tars dev --help", to see all avaliable options.
⠋🅃 🄰 🅁 🅂 : You can use interactive mode via starting tars without any flags.
⠋🅃 🄰 🅁 🅂 : Please wait for a moment, while I'm preparing builder for working...

[19:53:07] Using gulpfile ~/frontend/gulpfile.js
[19:53:07] Starting 'dev'...
[19:53:07] Starting 'main:dev'...
[19:53:07] Starting 'setWatchMode'...
[19:53:07] Finished 'setWatchMode' after 816 μs
[19:53:07] Starting 'main:build-dev'...
[19:53:07] Starting 'service:clean'...
[19:53:07] Finished 'service:clean' after 28 ms
[19:53:07] Starting 'images:minify-svg'...
[19:53:07] Starting 'images:raster-svg'...
[19:53:07] Skipped  'images:raster-svg' Rastering SVG is not used
[19:53:07] Finished 'images:raster-svg' after 215 ms
[19:53:07] gulp-imagemin: Minified 35 images (saved 187 B - 0.5%)
[19:53:07] Finished 'images:minify-svg' after 680 ms
[19:53:07] Starting 'css:make-sprite-for-svg'...
[19:53:07] Starting 'css:make-fallback-for-svg'...
[19:53:07] Starting 'css:make-sprite'...
[19:53:07] Starting 'images:make-symbols-sprite'...
[19:53:07] Skipped  'css:make-sprite-for-svg' SVG is not used or you prefer symbols workflow
[19:53:07] Skipped  'css:make-fallback-for-svg' Svg-fallback is not used


---------------------------------------------------------------------------------
'It seems, that TARS in current project is not compatible with current TARS-CLI!'
'Package "gulp-svg-symbols" is not available.'
'Update TARS-CLI via "tars update" and your project via "tars update-project"'
'Please, write to the tars.builder@gmail.com, if update did not help you.'
---------------------------------------------------------------------------------

[19:53:08] 'images:make-symbols-sprite' errored after 545 ms
[19:53:08] Error: Package gulp-svg-symbols is not available.
    at Object.tarsRequire [as require] (/frontend/tars/tars.js:43:19)
    at /frontend/tars/tasks/images/make-symbols-sprite.js:34:26
    at taskWrapper (/frontend/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (node:domain:433:15)
    at runBound (node:domain:444:12)
    at asyncRunner (/frontend/node_modules/async-done/index.js:55:18)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

[19:53:08] 'main:build-dev' errored after 1.26 s
[19:53:08] 'main:dev' errored after 1.26 s
[19:53:08] 'dev' errored after 1.26 s
```

Мое окружение для проекта было поставлено уже давно и все собиралось без ошибок. До того момента пока я сам не переустановил tars-cli. Теперь и у меня вылезает та же самая ошибка, и я не понимаю как вернуть все взад. 

Есть идеи?

**Comment by ncer** [comment]
К счастью, удалось раздобыть установленный tars-cli, который работал. Я заменил папку gulp-svg-symbols в свежескачанном tars-cli на такую же из старого tars-cli и все взлетело (на MacOS Sequoia 15.0.1 (24A348)).

Правда, начали сыпаться варнинги от sass. Это тоже удалось полечить заменой папки sass.

В общем, пока работать дальше можно, но с gulp-svg-symbols явно что-то не так.
