### ISSUE TITLE
Error on tars dev in Elementary OS

### ISSUE THREAD

**Issue by ilyoff** [tars/tars-cli#23]
Hello, I'm getting the following error on `tars dev` 

OS: Elementary OS
Node v0.10.39
npm 2.13.3
```
/usr/lib/node_modules/tars-cli/node_modules/gulp-importify/index.js:72
        extension = path.parse(file.path).ext.substr(1);
                         ^
TypeError: Object #<Object> has no method 'parse'
  at DestroyableTransform.bufferContents [as _transform] (/usr/lib/node_modules/tars-cli/node_modules/gulp-importify/index.js:72:26)
  at DestroyableTransform.Transform._read (/usr/lib/node_modules/tars-cli/node_modules/gulp-importify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/usr/lib/node_modules/tars-cli/node_modules/gulp-importify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/usr/lib/node_modules/tars-cli/node_modules/gulp-importify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/usr/lib/node_modules/tars-cli/node_modules/gulp-importify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/usr/lib/node_modules/tars-cli/node_modules/gulp-importify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at DestroyableTransform.ondata (/usr/lib/node_modules/tars-cli/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:578:20)
  at DestroyableTransform.emit (events.js:95:17)
  at readableAddChunk (/usr/lib/node_modules/tars-cli/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:199:16)
  at DestroyableTransform.Readable.push (/usr/lib/node_modules/tars-cli/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:163:10)
  at DestroyableTransform.Transform.push (/usr/lib/node_modules/tars-cli/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:133:32)
  at DestroyableTransform.sourceMapInit [as _transform] (/usr/lib/node_modules/tars-cli/node_modules/gulp-sourcemaps/index.js:122:10)
  at DestroyableTransform.Transform._read (/usr/lib/node_modules/tars-cli/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
  at DestroyableTransform.Transform._write (/usr/lib/node_modules/tars-cli/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
  at doWrite (/usr/lib/node_modules/tars-cli/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:333:12)
  at writeOrBuffer (/usr/lib/node_modules/tars-cli/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:319:5)
  at DestroyableTransform.Writable.write (/usr/lib/node_modules/tars-cli/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:246:11)
  at write (/usr/lib/node_modules/tars-cli/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/usr/lib/node_modules/tars-cli/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/usr/lib/node_modules/tars-cli/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:117:20)
  at emitReadable_ (/usr/lib/node_modules/tars-cli/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/usr/lib/node_modules/tars-cli/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/usr/lib/node_modules/tars-cli/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/usr/lib/node_modules/tars-cli/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/usr/lib/node_modules/tars-cli/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/usr/lib/node_modules/tars-cli/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/usr/lib/node_modules/tars-cli/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at DestroyableTransform.noop [as _transform] (/usr/lib/node_modules/tars-cli/node_modules/gulp-plumber/node_modules/through2/through2.js:26:3)
  at DestroyableTransform.Transform._read (/usr/lib/node_modules/tars-cli/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/usr/lib/node_modules/tars-cli/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/usr/lib/node_modules/tars-cli/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/usr/lib/node_modules/tars-cli/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/usr/lib/node_modules/tars-cli/node_modules/gulp-plumber/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at write (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:92:17)
  at emitReadable_ (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at DestroyableTransform.noop [as _transform] (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/through2.js:26:3)
  at DestroyableTransform.Transform._read (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at write (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:92:17)
  at emitReadable_ (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at /home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:12:5
  at evalmachine.<anonymous>:272:14
  at /home/ilyoff/Documents/Projects/freelance/tars/node_modules/gulp/node_modules/vinyl-fs/node_modules/graceful-fs/graceful-fs.js:102:5
  at Object.oncomplete (evalmachine.<anonymous>:108:15)
```

**Comment by artem-malko** [comment]
Oh, I've never heard about Elementary OS) What kind of 
Could you run some commands and write logs here?
First of all, could you run node and run the follow script:
````javascript
require('path').resolve('./qwe/asd');
````
The second command:
````javascript
require('os').type();
require('os').platform();
````
Thank you for bug-request. I will try to fix it asap after your answers.

**Comment by ilyoff** [comment]
@artem-malko it is based on ubuntu https://elementary.io

Here is the output
```
require('path').resolve('./qwe/asd');
'/home/ilyoff/qwe/asd'
```

```
> require('os').type();
'Linux'
> require('os').platform();
'linux'
```

**Comment by artem-malko** [comment]
I advice you to update your node.js Can you update it to 4.x.x version?

**Comment by artem-malko** [comment]
@ilyoff please, give a feedback if it works for you.

**Comment by ilyoff** [comment]
@artem-malko Yes, it worked for me. I've updated nodejs to 4.2.1 version, then I updated tars-cli and it worked. Thank you for help and tool =)

**Comment by artem-malko** [comment]
@ilyoff nice! You are welcome)
