### ISSUE TITLE
TARS doesn't work with node v6.5.0

### ISSUE THREAD

**Issue by bautrukevich** [tars/tars-cli#61]
TARS doesn't work with node v6.5.0 even after update cli and update project, reinstall node modules.
Stack trace:
[17:27:37] Error in plugin 'run-sequence(css:compile-css)'
Message:
    Package gulp-sass is not available.
Stack:
Error: Package gulp-sass is not available.
  at Object.tarsRequire [as require] (/Users/z/Code/fiat-m.local/tars/tars.js:34:19)
  at Object.preprocessor (/Users/z/Code/fiat-m.local/tars/tars.js:237:38)
  at generateTaskContent (/Users/z/Code/fiat-m.local/tars/tasks/css/helpers/manual-compile-css-task-template.js:90:31)
  at Gulp.tars.packages.gulp.task (/Users/z/Code/fiat-m.local/tars/tasks/css/compile-css.js:8:111)
  at module.exports (/Users/z/Code/fiat-m.local/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/Users/z/Code/fiat-m.local/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/Users/z/Code/fiat-m.local/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/Users/z/Code/fiat-m.local/node_modules/orchestrator/index.js:134:8)
  at runNextSet (/usr/local/lib/node_modules/tars-cli/node_modules/run-sequence/index.js:86:16)
  at Gulp.onTaskEnd (/usr/local/lib/node_modules/tars-cli/node_modules/run-sequence/index.js:75:5)
  at emitOne (events.js:101:20)
  at Gulp.emit (events.js:188:7)
  at Gulp.Orchestrator._emitTaskDone (/Users/z/Code/fiat-m.local/node_modules/orchestrator/index.js:264:8)
  at /Users/z/Code/fiat-m.local/node_modules/orchestrator/index.js:275:23
  at finish (/Users/z/Code/fiat-m.local/node_modules/orchestrator/lib/runTask.js:21:8)
  at /Users/z/Code/fiat-m.local/node_modules/orchestrator/lib/runTask.js:52:4
  at f (/Users/z/Code/fiat-m.local/node_modules/once/once.js:17:25)
  at DestroyableTransform.onend (/Users/z/Code/fiat-m.local/node_modules/end-of-stream/index.js:31:18)
  at emitNone (events.js:91:20)
  at DestroyableTransform.emit (events.js:185:7)
  at endReadableNT (/usr/local/lib/node_modules/tars-cli/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:865:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)

Install and reinstall node-sass, gulp-sass doesn't help too.
What's problem?

**Comment by artem-malko** [comment]
@bautrukevich try to run:
```bash
npm un -g tars-cli
npm i -g tars-cli
```
Do you have Windows?

**Comment by bautrukevich** [comment]
@artem-malko no, it's on MacOS. Thank's! It helped.
