### ISSUE TITLE
Не компилируется tars-cli

### ISSUE THREAD

**Issue by rucomcode** [tars/tars-cli#79]
Валиться вот на такой ошибке
`fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory`
Полный вывод:
```
npm WARN deprecated gulp-util@3.0.7: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated gulp-util@0.0.1: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated jade@1.9.2: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> tars-cli@1.9.5 postuninstall C:\Users\gonch\AppData\Roaming\npm\node_modules\tars-cli
> node ./lib/npm-scripts/postuninstall.js


I hope, I was helpful!
Please, send a feedback to tars.builder@gmail.com if you have something to say.

C:\Users\gonch\AppData\Roaming\npm\tars -> C:\Users\gonch\AppData\Roaming\npm\node_modules\tars-cli\bin\tars.js

> posix@4.1.1 install C:\Users\gonch\AppData\Roaming\npm\node_modules\tars-cli\node_modules\posix
> node-gyp rebuild


C:\Users\gonch\AppData\Roaming\npm\node_modules\tars-cli\node_modules\posix>if not defined npm_config_node_gyp (node "C:\Users\gonch\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\gonch\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, добавьте параметр "/m".
  posix.cc
  win_delay_load_hook.cc
..\src\posix.cc(2): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [C:\Users\gonch\AppData\Roaming\npm\node_modules\tars-cli\node_modules\posix\build\posix.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\gonch\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gonch\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\npm-lifecycle\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\gonch\AppData\Roaming\npm\node_modules\tars-cli\node_modules\posix
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\tars-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: posix@4.1.1 (node_modules\tars-cli\node_modules\posix):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: posix@4.1.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ tars-cli@1.9.5
updated 1 package in 139.258s
```

**Comment by artem-malko** [comment]
Завтра будет апдейт)

**Comment by artem-malko** [comment]
Fixed in 1.9.8

**Comment by rucomcode** [comment]
```
npm i -g tars-cli
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated gulp-util@0.0.1: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated jade@1.9.2: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> tars-cli@1.9.8 postuninstall C:\Users\Xiaomi\AppData\Roaming\npm\node_modules\tars-cli
> node ./lib/npm-scripts/postuninstall.js


I hope, I was helpful!
Please, send a feedback to tars.builder@gmail.com if you have something to say.

C:\Users\Xiaomi\AppData\Roaming\npm\tars -> C:\Users\Xiaomi\AppData\Roaming\npm\node_modules\tars-cli\bin\tars.js

> posix@4.1.2 install C:\Users\Xiaomi\AppData\Roaming\npm\node_modules\tars-cli\node_modules\posix
> node-gyp rebuild


C:\Users\Xiaomi\AppData\Roaming\npm\node_modules\tars-cli\node_modules\posix>if not defined npm_config_node_gyp (node "C:\Users\Xiaomi\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Xiaomi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Выполняется последовательная сборка проектов в этом решении. Чтобы включить параллельную сборку, добавьте параметр "/m".
  posix.cc
  win_delay_load_hook.cc
c:\users\xiaomi\appdata\roaming\npm\node_modules\tars-cli\node_modules\posix\src\posix.cc(2): fatal error C1083: Не удается открыть файл включение: unistd.h: No such file or directory, [C:\Users\Xiaomi\AppData\ Roaming\npm\node_modules\tars-cli\node_modules\posix\build\posix.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Xiaomi\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Xiaomi\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Xiaomi\AppData\Roaming\npm\node_modules\tars-cli\node_modules\posix
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN eslint-loader@2.1.1 requires a peer of webpack@>=2.0.0 <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\tars-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: posix@4.1.2 (node_modules\tars-cli\node_modules\posix):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: posix@4.1.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by rucomcode** [comment]
Опять то же самое
WTF, этот виндовс достал уже. В UNIX системе все ставиться на раз-два-три

**Comment by artem-malko** [comment]
Не совсем уверен, но можно попробовать переустановить Visual Studio

**Comment by rucomcode** [comment]
> Не совсем уверен, но можно попробовать переустановить Visual Studio

Обновлял уже десять раз windows-build-tools но оно нифига не помогает. И куда копать вообще не понятно. Хотя бы кто помог бы.

**Comment by artem-malko** [comment]
@rucomcode погоди, судя по логу — все нормально заканчивается, нет выхода с кодом > 0

**Comment by rucomcode** [comment]
> @rucomcode погоди, судя по логу — все нормально заканчивается, нет выхода с кодом > 0

Но после такой "установки" ничего не собирается. Валиться с ошибкой

`[09:40:53] Starting 'html:compile-templates'...
[09:40:53] gulp-notify: [TARS notification]
An error occurred while compiling to html.
Look in the console for details.

Error details:

An error occurred with data-files!
SyntaxError: Unexpected token <<`

**Comment by rucomcode** [comment]
@artem-malko прикол в том, что точно с такими же файлами на Linux и OSX все собирается с первого раза без приколючений

**Comment by artem-malko** [comment]
А что за контент в этом файле, в котором ошибка?

**Comment by rucomcode** [comment]
@artem-malko я оладушек.... Как то в файлы прокрался кусок с диффа и там естественно было `<<<` вот на него и ругалось
НО, факт остается фактом - на винде не собирается как надо, но работать не мешает

**Comment by artem-malko** [comment]
@rucomcode нет, все норм) Posix — это опциональная зависимость. На винде она не установится. Но это не мешает установке tars-cli.
