### ISSUE TITLE
Не обновляется tars-cli

### ISSUE THREAD

**Issue by Ivanopalas** [tars/tars-cli#91]
Не могу обновить. NPM cache почисти и все равно не хочет обновляться. Вот что выдает при попытке обновить — 
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2018-11-15T08_39_03_141Z-debug.log
child_process.js:644
    throw err;
    ^

Error: Command failed: npm cache clean
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2018-11-15T08_39_03_141Z-debug.log

    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at update (/usr/local/lib/node_modules/tars-cli/lib/command-actions/update.js:15:5)
    at Command.program.command.alias.description.action (/usr/local/lib/node_modules/tars-cli/bin/tars.js:137:59)
    at Command.listener (/usr/local/lib/node_modules/tars-cli/node_modules/commander/index.js:300:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/usr/local/lib/node_modules/tars-cli/node_modules/commander/index.js:635:12)
    at Command.parse (/usr/local/lib/node_modules/tars-cli/node_modules/commander/index.js:457:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/tars-cli/bin/tars.js:175:9)

**Comment by artem-malko** [comment]
Кажется старая версия ноды, меньше 8 точно. Предлагаю просто снести tars-cli и поставить снова.
